### ISSUE TITLE
telegram channel banned (for some people)

### ISSUE THREAD

**Issue by phanirithvij** [Zack-Bloodshot/AnimeWalls#1]
The @AnimeWallsForU channel on telegram was inaccessible for me since 4-5 months because of the reason `this channel cannot be displayed because it was used to spread *****graphic content`.
I think it is banned for for non us numbers (at least it is banned for Indian numbers).
Is it possible to restore it or can something be done?

**Comment by Zack-Bloodshot** [comment]
Yes, and sorry I have no intentions of bringing it back, instead you can check out [@Not_Anime_Wallpapers](https://t.me/Not_Anime_Wallpapers)
